POST http://localhost:3000/api/services
Content-Type: application/json

{
	"name": "Algum serviço",
	"description": "Alguma descrição",
	"price": 1400,
	"image": "https://fakeimg.pl/600x400"
}

###

GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/65b8c6b4de9e68e579976c92

###

DELETE http://localhost:3000/api/services/65b8c6b4de9e68e579976c92