POST http://localhost:3000/api/services
Content-Type: application/json

{
	"name": "Algum serviço",
	"description": "Alguma descrição",
	"price": 1400,
	"image": "https://fakeimg.pl/600x400"
}

###

GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/65b8c6b4de9e68e579976c92

###

DELETE http://localhost:3000/api/services/65b8c66f44fcbc3a7dbc40f1###

###

PUT http://localhost:3000/api/services/65b8cf6321cab21ed22dd887
Content-Type: application/json

{
	"name": "TESTE ATUALIZAÇÃO",
	"description": "Alguma descrição",
	"price": 1400,
	"image": "https://fakeimg.pl/600x400"
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
	"title": "Meu evento",
	"author": "Gabriel",
	"description": "Uma festa de aniversário",
	"budget": 5000,
	"image": "https://fakeimg.pl/600x400",
	"services": [
		{
			"name": "Algum serviço",
			"description": "Alguma descrição",
			"price": 1400,
			"image": "https://fakeimg.pl/600x400"
		}
	]
}

###

GET http://localhost:3000/api/parties
Content-Type: application/json

### 

GET http://localhost:3000/api/parties/65ba3e8edff3021bcfffbb58
Content-Type: application/json

###

PUT http://localhost:3000/api/parties/65ba4578e443d40ea0bc8bc6
Content-Type: application/json

{
	"title": "Meu evento 3",
	"author": "Gabriel",
	"description": "Uma festa de aniversário",
	"budget": 5000,
	"image": "https://fakeimg.pl/600x400",
	"services": [
		{
			"name": "Algum serviço",
			"description": "Alguma descrição",
			"price": 1400,
			"image": "https://fakeimg.pl/600x400"
		}
	]
}

###

DELETE http://localhost:3000/api/parties/65ba4578e443d40ea0bc8bc6
Content-Type: application/json
